# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

createModel <- function() {
    invisible(.Call('_rfuse_createModel', PACKAGE = 'rfuse'))
}

deleteModel <- function() {
    invisible(.Call('_rfuse_deleteModel', PACKAGE = 'rfuse'))
}

freeCspace <- function() {
    invisible(.Call('_rfuse_freeCspace', PACKAGE = 'rfuse'))
}

startTiming <- function() {
    invisible(.Call('_rfuse_startTiming', PACKAGE = 'rfuse'))
}

endTiming <- function(print = 1L) {
    invisible(.Call('_rfuse_endTiming', PACKAGE = 'rfuse', print))
}

getEdgelist2 <- function(Sfuse, Mat, nCORES, Norm2 = 0L) {
    .Call('_rfuse_getEdgelist2', PACKAGE = 'rfuse', Sfuse, Mat, nCORES, Norm2)
}

getEdgelist <- function(Min, nCORES, Norm2 = 0L) {
    .Call('_rfuse_getEdgelist', PACKAGE = 'rfuse', Min, nCORES, Norm2)
}

tcpp <- function(Min, nCORES) {
    invisible(.Call('_rfuse_tcpp', PACKAGE = 'rfuse', Min, nCORES))
}

readPmatrix <- function(Pmat, Dataset, nCORES) {
    invisible(.Call('_rfuse_readPmatrix', PACKAGE = 'rfuse', Pmat, Dataset, nCORES))
}

readSmatrix2 <- function(Smat, Dataset, nCORES) {
    invisible(.Call('_rfuse_readSmatrix2', PACKAGE = 'rfuse', Smat, Dataset, nCORES))
}

readSmatrix <- function(Smat, Dataset, nCORES) {
    invisible(.Call('_rfuse_readSmatrix', PACKAGE = 'rfuse', Smat, Dataset, nCORES))
}

normalisePc <- function(Pcmat, nCORES) {
    invisible(.Call('_rfuse_normalisePc', PACKAGE = 'rfuse', Pcmat, nCORES))
}

test <- function(Pmat, Smat, Dataset, nCORES) {
    invisible(.Call('_rfuse_test', PACKAGE = 'rfuse', Pmat, Smat, Dataset, nCORES))
}

findASDedges <- function(Pfuse, nCORES, nSTEPS = 0L) {
    .Call('_rfuse_findASDedges', PACKAGE = 'rfuse', Pfuse, nCORES, nSTEPS)
}

findCONTROLedges <- function(Pfuse, nCORES, nSTEPS = 0L) {
    .Call('_rfuse_findCONTROLedges', PACKAGE = 'rfuse', Pfuse, nCORES, nSTEPS)
}

fuseASDsets <- function(Pfuse, nCORES, nTHREADS = 1L, nSTEPS = 20L) {
    .Call('_rfuse_fuseASDsets', PACKAGE = 'rfuse', Pfuse, nCORES, nTHREADS, nSTEPS)
}

fuseCONTROLsets <- function(Pfuse, nCORES, nTHREADS = 1L, nSTEPS = 20L) {
    .Call('_rfuse_fuseCONTROLsets', PACKAGE = 'rfuse', Pfuse, nCORES, nTHREADS, nSTEPS)
}

